//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.chbase.android.simplexml.things.types.sleepsessionv2;

import com.chbase.android.simplexml.things.thing.AbstractThing;
import com.chbase.android.simplexml.things.types.base.CodableValue;
import com.chbase.android.simplexml.things.types.dates.DateTime;
import com.chbase.android.simplexml.things.types.dates.Time;

import org.simpleframework.xml.Element;
import org.simpleframework.xml.ElementList;
import org.simpleframework.xml.Order;
import org.simpleframework.xml.Root;

import java.util.ArrayList;
import java.util.List;

/**
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
 * 				Schema for a morning sleep journal.&#13;
 * 			  &lt;/summary&gt;
 * </pre>
 * 
 *           
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;remarks xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
 * 				A morning sleep journal reflects back on the previous nights&#13;
 * 				sleep. The data items were adapted from the SleepJournalAM datatype and common data from wearable device.&#13;
 * 			  &lt;/remarks&gt;
 * </pre>
 * 
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="when" type="{urn:com.microsoft.wc.dates}date-time"/>
 *         <element name="bed-time" type="{urn:com.microsoft.wc.dates}time"/>
 *         <element name="wake-time" type="{urn:com.microsoft.wc.dates}time"/>
 *         <element name="sleep-minutes" type="{urn:com.microsoft.wc.thing.types}nonNegativeInt"/>
 *         <element name="settling-minutes" type="{urn:com.microsoft.wc.thing.types}nonNegativeInt" minOccurs="0"/>
 *         <element name="awakening" type="{urn:com.microsoft.wc.thing.ssv2}Awakening" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="medications" type="{urn:com.microsoft.wc.thing.types}codable-value" minOccurs="0"/>
 *         <element name="wake-state" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               <minInclusive value="1"/>
 *               <maxInclusive value="3"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="light-sleep-duration" type="{urn:com.microsoft.wc.thing.types}nonNegativeInt" minOccurs="0"/>
 *         <element name="deep-sleep-duration" type="{urn:com.microsoft.wc.thing.types}nonNegativeInt" minOccurs="0"/>
 *         <element name="rem-sleep-duration" type="{urn:com.microsoft.wc.thing.types}nonNegativeInt" minOccurs="0"/>
 *         <element name="awake-duration" type="{urn:com.microsoft.wc.thing.types}nonNegativeInt" minOccurs="0"/>
 *         <element name="wakeup-duration" type="{urn:com.microsoft.wc.thing.types}nonNegativeInt" minOccurs="0"/>
 *         <element name="level" type="{urn:com.microsoft.wc.thing.ssv2}Level" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="times-woken-up" type="{urn:com.microsoft.wc.thing.types}nonNegativeInt" minOccurs="0"/>
 *         <element name="average-resting-hr" type="{urn:com.microsoft.wc.thing.types}nonNegativeInt" minOccurs="0"/>
 *         <element name="calories-burned" type="{urn:com.microsoft.wc.thing.types}nonNegativeInt" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */

@Order(elements= {
    "when",
    "bed-time",
    "wake-time",
    "sleep-minutes",
    "settling-minutes",
    "awakening",
    "medications",
    "wake-state",
    "light-sleep-duration",
    "deep-sleep-duration",
    "rem-sleep-duration",
    "awake-duration",
    "wakeup-duration",
    "level",
    "times-woken-up",
    "average-resting-hr",
    "calories-burned"
})
@Root(name = "sleep-session-v2")
public class SleepSessionV2 extends AbstractThing {

    public static String typeId = "902e1a03-d7c7-409b-b566-ceddd8b17297";

    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
     * 					The date and time that the journal entry refers to.&#13;
     * 				  &lt;/summary&gt;
     * </pre>
     * 
     */
    @Element(required = true)
    protected DateTime when;
    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
     * 					The time the person went to bed.&#13;
     * 				  &lt;/summary&gt;
     * </pre>
     * 
     */
    @Element(name = "bed-time", required = true)
    protected Time bedTime;
    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
     * 					The time the person woke up for a period of&#13;
     * 					activity.&#13;
     * 				  &lt;/summary&gt;
     * </pre>
     * 
     */
    @Element(name = "wake-time", required = true)
    protected Time wakeTime;
    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
     * 					The number of minutes slept.&#13;
     * 				  &lt;/summary&gt;
     * </pre>
     * 
     */
    @Element(name = "sleep-minutes")
    protected int sleepMinutes;
    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
     * 					The number of minutes it took to fall asleep.&#13;
     * 				  &lt;/summary&gt;
     * </pre>
     * 
     */
    @Element(name = "settling-minutes")
    protected Integer settlingMinutes;
    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
     * 					The time and duration of each the person awoke&#13;
     * 					during the night.&#13;
     * 				  &lt;/summary&gt;
     * </pre>
     * 
     */
    @ElementList(name = "awakening", inline = true,required = false)
    protected List<Awakening> awakening;
    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
     * 					A description of the medications taken before&#13;
     * 					going to bed.&#13;
     * 				  &lt;/summary&gt;
     * </pre>
     * 
     */
    @Element(name = "medications", required = false)
    protected CodableValue medications;
    @Element(name = "wake-state", required = false)
    protected Integer wakeState;
    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
     * 					The total number of seconds in a light sleep state.&#13;
     * 				  &lt;/summary&gt;
     * </pre>
     * 
     */
    @Element(name = "light-sleep-duration", required = false)
    protected Integer lightSleepDuration;
    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
     * 					The total number of seconds in a deep sleep state.&#13;
     * 				  &lt;/summary&gt;
     * </pre>
     * 
     */
    @Element(name = "deep-sleep-duration", required = false)
    protected Integer deepSleepDuration;
    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
     * 					The total number of seconds in a REM sleep state (https://en.wikipedia.org/wiki/Rapid_eye_movement_sleep).&#13;
     * 				  &lt;/summary&gt;
     * </pre>
     * 
     */
    @Element(name = "rem-sleep-duration", required = false)
    protected Integer remSleepDuration;
    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
     * 					The total number of seconds in a wake state.&#13;
     * 				  &lt;/summary&gt;
     * </pre>
     * 
     */
    @Element(name = "awake-duration",required = false)
    protected Integer awakeDuration;
    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
     * 					The total number of seconds after waking up.&#13;
     * 				  &lt;/summary&gt;
     * </pre>
     * 
     */
    @Element(name = "wakeup-duration", required = false)
    protected Integer wakeupDuration;
    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
     * 					A collection representing each of the person's sleep sates that include a start time, the title of the state, and a duration.&#13;
     * 				  &lt;/summary&gt;
     * </pre>
     * 
     */
    @ElementList(name = "sleep-minutes", inline = true,required = false)
    protected List<Level> level;
    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt; The number of times the person woke up at night. &lt;/summary&gt;
     * </pre>
     * 
     */
    @Element(name = "times-woken-up", required = false)
    protected Integer timesWokenUp;
    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt; The average resting heart rate of the person. &lt;/summary&gt;
     * </pre>
     * 
     */
    @Element(name = "average-resting-hr",required = false)
    protected Integer averageRestingHr;
    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt; The number of calories burned while sleeping. &lt;/summary&gt;
     * </pre>
     * 
     */
    @Element(name = "calories-burned",required = false)
    protected Integer caloriesBurned;

    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
     * 					The date and time that the journal entry refers to.&#13;
     * 				  &lt;/summary&gt;
     * </pre>
     * 
     * @return
     *     possible object is
     *     {@link DateTime }
     *     
     */
    public DateTime getWhen() {
        return when;
    }

    /**
     * Sets the value of the when property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTime }
     *     
     * @see #getWhen()
     */
    public void setWhen(DateTime value) {
        this.when = value;
    }

    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
     * 					The time the person went to bed.&#13;
     * 				  &lt;/summary&gt;
     * </pre>
     * 
     * @return
     *     possible object is
     *     {@link Time }
     *     
     */
    public Time getBedTime() {
        return bedTime;
    }

    /**
     * Sets the value of the bedTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Time }
     *     
     * @see #getBedTime()
     */
    public void setBedTime(Time value) {
        this.bedTime = value;
    }

    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
     * 					The time the person woke up for a period of&#13;
     * 					activity.&#13;
     * 				  &lt;/summary&gt;
     * </pre>
     * 
     * @return
     *     possible object is
     *     {@link Time }
     *     
     */
    public Time getWakeTime() {
        return wakeTime;
    }

    /**
     * Sets the value of the wakeTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Time }
     *     
     * @see #getWakeTime()
     */
    public void setWakeTime(Time value) {
        this.wakeTime = value;
    }

    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
     * 					The number of minutes slept.&#13;
     * 				  &lt;/summary&gt;
     * </pre>
     * 
     */
    public int getSleepMinutes() {
        return sleepMinutes;
    }

    /**
     * Sets the value of the sleepMinutes property.
     * 
     */
    public void setSleepMinutes(int value) {
        this.sleepMinutes = value;
    }

    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
     * 					The number of minutes it took to fall asleep.&#13;
     * 				  &lt;/summary&gt;
     * </pre>
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSettlingMinutes() {
        return settlingMinutes;
    }

    /**
     * Sets the value of the settlingMinutes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getSettlingMinutes()
     */
    public void setSettlingMinutes(Integer value) {
        this.settlingMinutes = value;
    }

    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
     * 					The time and duration of each the person awoke&#13;
     * 					during the night.&#13;
     * 				  &lt;/summary&gt;
     * </pre>
     * 
     * Gets the value of the awakening property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the awakening property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getAwakening().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Awakening }
     * </p>
     * 
     * 
     * @return
     *     The value of the awakening property.
     */
    public List<Awakening> getAwakening() {
        if (awakening == null) {
            awakening = new ArrayList<>();
        }
        return this.awakening;
    }

    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
     * 					A description of the medications taken before&#13;
     * 					going to bed.&#13;
     * 				  &lt;/summary&gt;
     * </pre>
     * 
     * @return
     *     possible object is
     *     {@link CodableValue }
     *     
     */
    public CodableValue getMedications() {
        return medications;
    }

    /**
     * Sets the value of the medications property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodableValue }
     *     
     * @see #getMedications()
     */
    public void setMedications(CodableValue value) {
        this.medications = value;
    }

    /**
     * Gets the value of the wakeState property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWakeState() {
        return wakeState;
    }

    /**
     * Sets the value of the wakeState property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWakeState(Integer value) {
        this.wakeState = value;
    }

    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
     * 					The total number of seconds in a light sleep state.&#13;
     * 				  &lt;/summary&gt;
     * </pre>
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLightSleepDuration() {
        return lightSleepDuration;
    }

    /**
     * Sets the value of the lightSleepDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getLightSleepDuration()
     */
    public void setLightSleepDuration(Integer value) {
        this.lightSleepDuration = value;
    }

    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
     * 					The total number of seconds in a deep sleep state.&#13;
     * 				  &lt;/summary&gt;
     * </pre>
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDeepSleepDuration() {
        return deepSleepDuration;
    }

    /**
     * Sets the value of the deepSleepDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getDeepSleepDuration()
     */
    public void setDeepSleepDuration(Integer value) {
        this.deepSleepDuration = value;
    }

    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
     * 					The total number of seconds in a REM sleep state (https://en.wikipedia.org/wiki/Rapid_eye_movement_sleep).&#13;
     * 				  &lt;/summary&gt;
     * </pre>
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRemSleepDuration() {
        return remSleepDuration;
    }

    /**
     * Sets the value of the remSleepDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getRemSleepDuration()
     */
    public void setRemSleepDuration(Integer value) {
        this.remSleepDuration = value;
    }

    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
     * 					The total number of seconds in a wake state.&#13;
     * 				  &lt;/summary&gt;
     * </pre>
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAwakeDuration() {
        return awakeDuration;
    }

    /**
     * Sets the value of the awakeDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getAwakeDuration()
     */
    public void setAwakeDuration(Integer value) {
        this.awakeDuration = value;
    }

    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
     * 					The total number of seconds after waking up.&#13;
     * 				  &lt;/summary&gt;
     * </pre>
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWakeupDuration() {
        return wakeupDuration;
    }

    /**
     * Sets the value of the wakeupDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getWakeupDuration()
     */
    public void setWakeupDuration(Integer value) {
        this.wakeupDuration = value;
    }

    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
     * 					A collection representing each of the person's sleep sates that include a start time, the title of the state, and a duration.&#13;
     * 				  &lt;/summary&gt;
     * </pre>
     * 
     * Gets the value of the level property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the level property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getLevel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Level }
     * </p>
     * 
     * 
     * @return
     *     The value of the level property.
     */
    public List<Level> getLevel() {
        if (level == null) {
            level = new ArrayList<>();
        }
        return this.level;
    }

    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt; The number of times the person woke up at night. &lt;/summary&gt;
     * </pre>
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTimesWokenUp() {
        return timesWokenUp;
    }

    /**
     * Sets the value of the timesWokenUp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getTimesWokenUp()
     */
    public void setTimesWokenUp(Integer value) {
        this.timesWokenUp = value;
    }

    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt; The average resting heart rate of the person. &lt;/summary&gt;
     * </pre>
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAverageRestingHr() {
        return averageRestingHr;
    }

    /**
     * Sets the value of the averageRestingHr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getAverageRestingHr()
     */
    public void setAverageRestingHr(Integer value) {
        this.averageRestingHr = value;
    }

    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt; The number of calories burned while sleeping. &lt;/summary&gt;
     * </pre>
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCaloriesBurned() {
        return caloriesBurned;
    }

    /**
     * Sets the value of the caloriesBurned property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getCaloriesBurned()
     */
    public void setCaloriesBurned(Integer value) {
        this.caloriesBurned = value;
    }

    @Override
    public String getThingType() {
        return typeId;
    }
}
