//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//

package com.chbase.android.simplexml.things.types.advancedirectivev2;

import com.chbase.android.simplexml.things.thing.AbstractThing;
import com.chbase.android.simplexml.things.types.dates.DateTime;

import org.simpleframework.xml.Element;
import org.simpleframework.xml.ElementList;
import org.simpleframework.xml.Order;
import org.simpleframework.xml.Root;

import java.util.ArrayList;
import java.util.List;

/**
 * <p>
 * Java class for anonymous complex type
 * </p>
 * .
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * </p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="when" type="{urn:com.microsoft.wc.dates}date-time"/>
 *         <element name="name" type=
"{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="contact" type=
"{urn:com.microsoft.wc.thing.advancedirectivev2}advance-directive-contact-type" maxOccurs
="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */

@Order( elements = {
        "when",
        "name",
        "contact"
})
@Root(name = "advance-directive-v2")
public class AdvanceDirectiveV2 extends AbstractThing {
    public static String typeId = "0e17be0f-4423-4220-a110-e879074cbfe0";
    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:advancedirectivev2="urn:com.microsoft.wc.thing.advancedirectivev2" xmlns:d="urn:com.microsoft.wc.dates" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
     *                 Date when the advance directive was uploaded.&#13;
     *               &lt;/summary&gt;
     * </pre>
     * 
     */
    @Element(required = true,name="when")
    protected DateTime when;
    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:advancedirectivev2="urn:com.microsoft.wc.thing.advancedirectivev2" xmlns:d="urn:com.microsoft.wc.dates" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;Name that denotes the advance directive&lt;/summary&gt;
     * </pre>
     * 
     */
    @Element(name="name")
    protected String name;
    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:advancedirectivev2="urn:com.microsoft.wc.thing.advancedirectivev2" xmlns:d="urn:com.microsoft.wc.dates" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;Contact information of persons related to this directive&lt;/summary&gt;
     * </pre>
     * 
     */
    @ElementList(entry="contact", inline = true)
    protected ArrayList<AdvanceDirectiveContactType> contact;

    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:advancedirectivev2="urn:com.microsoft.wc.thing.advancedirectivev2" xmlns:d="urn:com.microsoft.wc.dates" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
     *                 Date when the advance directive was uploaded.&#13;
     *               &lt;/summary&gt;
     * </pre>
     * 
     * @return
     *         possible object is
     *         {@link DateTime }
     * 
     */
    public DateTime getWhen() {
        return when;
    }

    /**
     * Sets the value of the when property.
     * 
     * @param value
     *              allowed object is
     *              {@link DateTime }
     * 
     * @see #getWhen()
     */
    public void setWhen(DateTime value) {
        this.when = value;
    }

    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:advancedirectivev2="urn:com.microsoft.wc.thing.advancedirectivev2" xmlns:d="urn:com.microsoft.wc.dates" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;Name that denotes the advance directive&lt;/summary&gt;
     * </pre>
     * 
     * @return
     *         possible object is
     *         {@link String }
     * 
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *              allowed object is
     *              {@link String }
     * 
     * @see #getName()
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:advancedirectivev2="urn:com.microsoft.wc.thing.advancedirectivev2" xmlns:d="urn:com.microsoft.wc.dates" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;Contact information of persons related to this directive&lt;/summary&gt;
     * </pre>
     * 
     * Gets the value of the contact property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contact property.
     * </p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * 
     * <pre>
     * getContact().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdvanceDirectiveContactType }
     * </p>
     * 
     * 
     * @return
     *         The value of the contact property.
     */
    public List<AdvanceDirectiveContactType> getContact() {
        if (contact == null) {
            contact = new ArrayList<>();
        }
        return this.contact;
    }

    @Override
    public String getThingType() {
        return AdvanceDirectiveV2.typeId;
    }
}
