//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.chbase.android.simplexml.things.types.advancedirectivev2;


import com.chbase.android.simplexml.things.types.base.CodableValue;
import com.chbase.android.simplexml.things.types.base.Contact;
import com.chbase.android.simplexml.things.types.base.Name;

import org.simpleframework.xml.Element;
import org.simpleframework.xml.Order;

/**
 * <p>Java class for advance-directive-contact-type complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="advance-directive-contact-type">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="name" type="{urn:com.microsoft.wc.thing.types}name" minOccurs="0"/>
 *         <element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="contact-info" type="{urn:com.microsoft.wc.thing.types}contact" minOccurs="0"/>
 *         <element name="relationship" type="{urn:com.microsoft.wc.thing.types}codable-value" minOccurs="0"/>
 *         <element name="is-primary" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */

@Order( elements = {
    "name",
    "id",
    "contact-info",
    "relationship",
    "is-primary"
})
public class AdvanceDirectiveContactType {

    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:advancedirectivev2="urn:com.microsoft.wc.thing.advancedirectivev2" xmlns:d="urn:com.microsoft.wc.dates" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;Name of the contact&lt;/summary&gt;
     * </pre>
     * 
     */
    @Element(name = "name",required = false)
    protected Name name;
    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:advancedirectivev2="urn:com.microsoft.wc.thing.advancedirectivev2" xmlns:d="urn:com.microsoft.wc.dates" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;Identifier for the contact&lt;/summary&gt;
     * </pre>
     * 
     */
    @Element(name = "id",required = false)
    protected String id;
    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:advancedirectivev2="urn:com.microsoft.wc.thing.advancedirectivev2" xmlns:d="urn:com.microsoft.wc.dates" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;Contact information of the person&lt;/summary&gt;
     * </pre>
     * 
     */
    @Element(name = "contact-info",required = false)
    protected Contact contactInfo;
    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:advancedirectivev2="urn:com.microsoft.wc.thing.advancedirectivev2" xmlns:d="urn:com.microsoft.wc.dates" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;Relationship with the subject&lt;/summary&gt;
     * </pre>
     * 
     */
    @Element(name = "relationship",required = false)
    protected CodableValue relationship;
    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:advancedirectivev2="urn:com.microsoft.wc.thing.advancedirectivev2" xmlns:d="urn:com.microsoft.wc.dates" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;Is the contact primary for this advance directive&lt;/summary&gt;
     * </pre>
     * 
     */
    @Element(name = "is-primary",required = false)
    protected Boolean isPrimary;

    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:advancedirectivev2="urn:com.microsoft.wc.thing.advancedirectivev2" xmlns:d="urn:com.microsoft.wc.dates" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;Name of the contact&lt;/summary&gt;
     * </pre>
     * 
     * @return
     *     possible object is
     *     {@link Name }
     *     
     */
    public Name getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link Name }
     *     
     * @see #getName()
     */
    public void setName(Name value) {
        this.name = value;
    }

    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:advancedirectivev2="urn:com.microsoft.wc.thing.advancedirectivev2" xmlns:d="urn:com.microsoft.wc.dates" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;Identifier for the contact&lt;/summary&gt;
     * </pre>
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getId()
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:advancedirectivev2="urn:com.microsoft.wc.thing.advancedirectivev2" xmlns:d="urn:com.microsoft.wc.dates" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;Contact information of the person&lt;/summary&gt;
     * </pre>
     * 
     * @return
     *     possible object is
     *     {@link Contact }
     *     
     */
    public Contact getContactInfo() {
        return contactInfo;
    }

    /**
     * Sets the value of the contactInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Contact }
     *     
     * @see #getContactInfo()
     */
    public void setContactInfo(Contact value) {
        this.contactInfo = value;
    }

    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:advancedirectivev2="urn:com.microsoft.wc.thing.advancedirectivev2" xmlns:d="urn:com.microsoft.wc.dates" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;Relationship with the subject&lt;/summary&gt;
     * </pre>
     * 
     * @return
     *     possible object is
     *     {@link CodableValue }
     *     
     */
    public CodableValue getRelationship() {
        return relationship;
    }

    /**
     * Sets the value of the relationship property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodableValue }
     *     
     * @see #getRelationship()
     */
    public void setRelationship(CodableValue value) {
        this.relationship = value;
    }

    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:advancedirectivev2="urn:com.microsoft.wc.thing.advancedirectivev2" xmlns:d="urn:com.microsoft.wc.dates" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;Is the contact primary for this advance directive&lt;/summary&gt;
     * </pre>
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsPrimary() {
        return isPrimary;
    }

    /**
     * Sets the value of the isPrimary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     * @see #isIsPrimary()
     */
    public void setIsPrimary(Boolean value) {
        this.isPrimary = value;
    }

}
