[versions]
agp = "8.5.0"
commonsCodec = "1.17.2"
commonsCodecVersion = "1.9"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
simpleXml = "2.7.1"

[libraries]
commons-codec = { module = "commons-codec:commons-codec", version.ref = "commonsCodec" }
commons-codec-v19 = { module = "commons-codec:commons-codec", version.ref = "commonsCodecVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
simple-xml = { module = "org.simpleframework:simple-xml", version.ref = "simpleXml" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

